name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get branch names.
      id: branch-names
      uses: tj-actions/branch-names@v6
    - uses: actions/checkout@v3
      with:
        ref: ${{ steps.branch-names.outputs.head_ref_branch }}
    - name: Build
      run: cargo build --verbose
    - name: Get the current tag
      if: steps.branch-name.outputs.is_tag == 'true'  # Replaces: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "${{ steps.branch-name.outputs.tag }}"
    - name: Run tests
      run: cargo test --verbose
    - name: Check formatting
      run: cargo fmt --check
